version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: leaderboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboard
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leaderboard-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: leaderboard-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - leaderboard-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: leaderboard-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@leaderboard.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - leaderboard-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: leaderboard-redisinsight
    ports:
      - '${REDISINSIGHT_PORT:-5540}:5540'
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - leaderboard-network

  prometheus:
    image: prom/prometheus:latest
    container_name: leaderboard-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - leaderboard-network

  grafana:
    image: grafana/grafana:latest
    container_name: leaderboard-grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - leaderboard-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  leaderboard-network:
    driver: bridge
